Flatten anonymous functions
pegnet/LXR256 pull request #61
Opened 2020-01-09 21:38 UTC by Emyrk

2020-01-12 07:32 UTC, WhoSoup requested changes
I've already suggested this in the past on a slightly older implementation of LXR and it was merged at some point, then undone again.

See #42 #43 #48 and in particular #50, which contains data for why it wasn't implemented at the time.

Just ran it on two machines using a branch of [lxrhash-benchmark@flatten](https://github.com/WhoSoup/lxrhash-benchmark/tree/flatten) and once again got two conflicting results: 

windows, ryzen 3700x:
* flat: 86,421 hps (5401 per core)
* old: 82,895 hps (5180 per core)

Which is the 5% yield described in #50. 

ubuntu, i3-7100u:
* flat:  23,688 (5922 per core)
* old: 27,695 (6923 per core)

Which is a negative 15% drop over running closures. It seems to be highly dependent on hardware/platform whether or not it's a slight boost or a significant drop, and the default shouldn't be the one that has a potential for a significant drop.

I think it would be interesting to give people the option but they would have to benchmark it on their system first and then enable the 5% boost if it works for them. Unless you can figure out what factor dictates this.

2020-01-13 14:32 UTC, Emyrk commented
Very interesting. Maybe we should make the flatten the optional one then?

2020-01-13 14:34 UTC, WhoSoup commented
> Very interesting. Maybe we should make the flatten the optional one then?

Yeah, I was thinking something like `Hash` and `FlatHash` in lxrhash. then pegnetd can have a cmd line 'benchmark' option that tests them and they can change in the config file which they want to use.

2020-01-13 15:29 UTC, Emyrk commented
I think that way is fine. As for where to put the benchmark, maybe not in pegnetd. It would be nice if there was a benchmark tool all golang miners could just easily import to run. The orax miner has a benchmark function, the prosper does not.

2020-01-16 07:55 UTC, WhoSoup approved these changes

2020-01-24 17:11 UTC, merged